[Core] make Microsoft.Maui.dll trimmable
Related to 3c8e1581, this is part two.

I started off with ~27 illink warnings:

    src\Core\src\Platform\MauiContext.cs(86,50): error IL2091: Microsoft.Maui.MauiContext.<>c__DisplayClass14_0<TService>.<AddSpecific>b__1(): 'T' generic argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in 'System.Lazy<T>'. The generic parameter 'TService' of 'Microsoft.Maui.MauiContext.<>c__DisplayClass14_0<TService>' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    ILLink error IL2091: System.Lazy`1<TService> Microsoft.Maui.MauiContext/<>c__DisplayClass14_0`1::lazy: 'T' generic argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in 'System.Lazy<T>'. The generic parameter 'TService' of 'Microsoft.Maui.MauiContext.<>c__DisplayClass14_0<TService>' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    src\Core\src\Platform\MauiContext.cs(95,50): error IL2091: Microsoft.Maui.MauiContext.<>c__DisplayClass15_0<TService,TImplementation>.<AddSpecific>b__1(): 'T' generic argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in 'System.Lazy<T>'. The generic parameter 'TImplementation' of 'Microsoft.Maui.MauiContext.<>c__DisplayClass15_0<TService,TImplementation>' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    ILLink error IL2091: System.Lazy`1<TImplementation> Microsoft.Maui.MauiContext/<>c__DisplayClass15_0`2::lazy: 'T' generic argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in 'System.Lazy<T>'. The generic parameter 'TImplementation' of 'Microsoft.Maui.MauiContext.<>c__DisplayClass15_0<TService,TImplementation>' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    src\Core\src\HotReload\HotReloadHelper.cs(133,36): error IL2026: Microsoft.Maui.HotReload.MauiHotReloadHelper.<>c__DisplayClass17_0.<RegisterReplacedView>b__2(Assembly): Using member 'System.Reflection.Assembly.GetType(String)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Types might be removed.
    src\Core\src\HotReload\HotReloadExtensions.cs(44,4): error IL2080: Microsoft.Maui.HotReload.HotReloadExtensions.<getOnHotReloadMethods>d__2.MoveNext(): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods', 'DynamicallyAccessedMemberTypes.NonPublicMethods' in call to 'System.Type.GetMethods(BindingFlags)'. The field 'System.Type Microsoft.Maui.HotReload.HotReloadExtensions/<getOnHotReloadMethods>d__2::type' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    src\Core\src\Hosting\ImageSources\ImageSourceServiceCollectionExtensions.cs(12,4): error IL2091: Microsoft.Maui.Hosting.ImageSourceServiceCollectionExtensions.AddService<TImageSource,TImageSourceService>(IImageSourceServiceCollection): 'TImplementation' generic argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in 'Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<TService,TImplementation>(IServiceCollection)'. The generic parameter 'TImageSourceService' of 'Microsoft.Maui.Hosting.ImageSourceServiceCollectionExtensions.AddService<TImageSource,TImageSourceService>(IImageSourceServiceCollection)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    src\Core\src\Hosting\ImageSources\ImageSourceServiceProvider.cs(31,5): error IL2055: Microsoft.Maui.Hosting.ImageSourceServiceProvider.<GetImageSourceServiceType>b__9_0(Type): Call to 'System.Type.MakeGenericType(Type[])' can not be statically analyzed. It's not possible to guarantee the availability of requirements of the generic type.
    src\Core\src\Hosting\ImageSources\ImageSourceServiceProvider.cs(36,5): error IL2055: Microsoft.Maui.Hosting.ImageSourceServiceProvider.<GetImageSourceServiceType>b__9_0(Type): Call to 'System.Type.MakeGenericType(Type[])' can not be statically analyzed. It's not possible to guarantee the availability of requirements of the generic type.
    src\Core\src\Hosting\ImageSources\ImageSourceServiceProvider.cs(46,5): error IL2070: Microsoft.Maui.Hosting.ImageSourceServiceProvider.CreateImageSourceTypeCacheEntry(Type): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.Interfaces' in call to 'System.Type.GetInterface(String)'. The parameter 'type' of method 'Microsoft.Maui.Hosting.ImageSourceServiceProvider.CreateImageSourceTypeCacheEntry(Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    src\Core\src\Hosting\ImageSources\ImageSourceServiceProvider.cs(51,37): error IL2070: Microsoft.Maui.Hosting.ImageSourceServiceProvider.CreateImageSourceTypeCacheEntry(Type): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.Interfaces' in call to 'System.Type.GetInterfaces()'. The parameter 'type' of method 'Microsoft.Maui.Hosting.ImageSourceServiceProvider.CreateImageSourceTypeCacheEntry(Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    src\Core\src\Hosting\ImageSources\ImageSourceServiceProvider.cs(53,6): error IL2065: Microsoft.Maui.Hosting.ImageSourceServiceProvider.CreateImageSourceTypeCacheEntry(Type): Value passed to implicit 'this' parameter of method 'System.Type.GetInterface(String)' can not be statically determined and may not meet 'DynamicallyAccessedMembersAttribute' requirements.
    src\Core\src\Platform\MauiContext.cs(84,4): error IL2091: Microsoft.Maui.MauiContext.AddSpecific<TService>(Func<TService>): 'T' generic argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in 'System.Lazy<T>'. The generic parameter 'TService' of 'Microsoft.Maui.MauiContext.AddSpecific<TService>(Func<TService>)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    src\Core\src\Platform\MauiContext.cs(93,4): error IL2091: Microsoft.Maui.MauiContext.AddSpecific<TService,TImplementation>(Func<TImplementation>): 'T' generic argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in 'System.Lazy<T>'. The generic parameter 'TImplementation' of 'Microsoft.Maui.MauiContext.AddSpecific<TService,TImplementation>(Func<TImplementation>)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    src\Core\src\Hosting\MauiHandlersCollectionExtensions.cs(21,4): error IL2067: Microsoft.Maui.Hosting.MauiHandlersCollectionExtensions.AddHandler(IMauiHandlersCollection,Type,Type): 'implementationType' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in call to 'Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient(IServiceCollection,Type,Type)'. The parameter 'handlerType' of method 'Microsoft.Maui.Hosting.MauiHandlersCollectionExtensions.AddHandler(IMauiHandlersCollection,Type,Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    src\Core\src\Hosting\MauiHandlersCollectionExtensions.cs(29,4): error IL2087: Microsoft.Maui.Hosting.MauiHandlersCollectionExtensions.AddHandler<TType,TTypeRender>(IMauiHandlersCollection): 'implementationType' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in call to 'Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient(IServiceCollection,Type,Type)'. The generic parameter 'TTypeRender' of 'Microsoft.Maui.Hosting.MauiHandlersCollectionExtensions.AddHandler<TType,TTypeRender>(IMauiHandlersCollection)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    src\Core\src\Hosting\MauiHandlersCollectionExtensions.cs(14,5): error IL2072: Microsoft.Maui.Hosting.MauiHandlersCollectionExtensions.AddHandlers(IMauiHandlersCollection,Dictionary<Type,Type>): 'implementationType' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in call to 'Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient(IServiceCollection,Type,Type)'. The return value of method 'System.Collections.Generic.KeyValuePair<TKey,TValue>.Value.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    src\Core\src\Hosting\MauiHandlersCollectionExtensions.cs(44,4): error IL2067: Microsoft.Maui.Hosting.MauiHandlersCollectionExtensions.TryAddHandler(IMauiHandlersCollection,Type,Type): 'implementationType' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in call to 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddTransient(IServiceCollection,Type,Type)'. The parameter 'handlerType' of method 'Microsoft.Maui.Hosting.MauiHandlersCollectionExtensions.TryAddHandler(IMauiHandlersCollection,Type,Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    src\Core\src\Hosting\MauiHandlersCollectionExtensions.cs(52,4): error IL2087: Microsoft.Maui.Hosting.MauiHandlersCollectionExtensions.TryAddHandler<TType,TTypeRender>(IMauiHandlersCollection): 'implementationType' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in call to 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddTransient(IServiceCollection,Type,Type)'. The generic parameter 'TTypeRender' of 'Microsoft.Maui.Hosting.MauiHandlersCollectionExtensions.TryAddHandler<TType,TTypeRender>(IMauiHandlersCollection)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    src\Core\src\Hosting\MauiHandlersCollectionExtensions.cs(37,5): error IL2072: Microsoft.Maui.Hosting.MauiHandlersCollectionExtensions.TryAddHandlers(IMauiHandlersCollection,Dictionary<Type,Type>): 'implementationType' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in call to 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddTransient(IServiceCollection,Type,Type)'. The return value of method 'System.Collections.Generic.KeyValuePair<TKey,TValue>.Value.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    src\Core\src\HotReload\HotReloadHelper.cs(67,5): error IL2062: Microsoft.Maui.HotReload.MauiHotReloadHelper.GetReplacedView(IHotReloadableView): Value passed to parameter '#0' of method 'System.Object System.Activator::CreateInstance(System.Type)' can not be statically determined and may not meet 'DynamicallyAccessedMembersAttribute' requirements.
    src\Core\src\HotReload\HotReloadHelper.cs(67,5): error IL2062: Microsoft.Maui.HotReload.MauiHotReloadHelper.GetReplacedView(IHotReloadableView): Value passed to parameter '#0' of method 'System.Object System.Activator::CreateInstance(System.Type,System.Object[])' can not be statically determined and may not meet 'DynamicallyAccessedMembersAttribute' requirements.
    src\Core\src\HotReload\HotReloadHelper.cs(154,5): error IL2055: Microsoft.Maui.HotReload.MauiHotReloadHelper.RegisterHandler(KeyValuePair<Type,Type>,Type): Call to 'System.Type.MakeGenericType(Type[])' can not be statically analyzed. It's not possible to guarantee the availability of requirements of the generic type.
    src\Core\src\Hosting\Internal\MauiServiceProvider.cs(184,4): error IL2070: Microsoft.Maui.Hosting.Internal.MauiServiceProvider.CreateInstance(Type): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.NonPublicConstructors' in call to 'System.Type.GetConstructors(BindingFlags)'. The parameter 'implementationType' of method 'Microsoft.Maui.Hosting.Internal.MauiServiceProvider.CreateInstance(Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    src\Core\src\Hosting\Internal\MauiServiceProvider.cs(149,5): error IL2055: Microsoft.Maui.Hosting.Internal.MauiServiceProvider.GetService(Type,ServiceDescriptor,IEnumerable<ServiceDescriptor>): Call to 'System.Type.MakeGenericType(Type[])' can not be statically analyzed. It's not possible to guarantee the availability of requirements of the generic type.
    src\Core\src\Hosting\Internal\MauiServiceProvider.cs(149,5): error IL2077: Microsoft.Maui.Hosting.Internal.MauiServiceProvider.GetService(Type,ServiceDescriptor,IEnumerable<ServiceDescriptor>): '#0' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in call to 'System.Object System.Activator::CreateInstance(System.Type)'. The field 'System.Type Microsoft.Maui.Hosting.Internal.MauiServiceProvider::ListType' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
    src\Core\src\Hosting\Internal\MauiServiceProvider.cs(117,29): error IL2070: Microsoft.Maui.Hosting.Internal.MauiServiceProvider.GetServiceBaseTypes(Type): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.Interfaces' in call to 'System.Type.GetInterfaces()'. The parameter 'serviceType' of method 'Microsoft.Maui.Hosting.Internal.MauiServiceProvider.GetServiceBaseTypes(Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.

When building:

    > .\bin\dotnet\dotnet.exe build `
        .\src\Controls\samples\Controls.Sample.SingleProject\Maui.Controls.Sample.SingleProject.csproj `
        -f net6.0-android `
        -c Release `
        -p:SuppressTrimAnalysisWarnings=false `
        -p:TrimmerSingleWarn=false `
        -bl

I addressed each warning and ensured apps still start.

~~ Public API Changes ~~

Removed two methods because the linker cannot statically analyze
`Dictionary<Type,Type>`:

    public static partial class MauiHandlersCollectionExtensions
    {
        public static IMauiHandlersCollection AddHandlers(this IMauiHandlersCollection handlersCollection, Dictionary<Type, Type> handlers)
        public static IMauiHandlersCollection TryAddHandlers(this IMauiHandlersCollection handlersCollection, Dictionary<Type, Type> handlers)

Usage of this in `AddMauiControlsHandlers` should just call
`AddHandler()` for each type? No need for a `Dictionary`?

I loosed the generic constrains on one other method:

    public static IMauiHandlersCollection AddHandler<TType, TTypeRender>(this IMauiHandlersCollection handlersCollection)
    --    where TType : IView
    --    where TTypeRender : IViewHandler
    ++    where TType : IElement
    ++    where TTypeRender : IElementHandler

This allowed its usage for `Application` and `Window`.

~~ Results ~~

A Release build of `Maui.Controls.Sample.SingleProject.csproj` in bytes:

Before: 30193687
After:  30136343

    > apkdiff -f before.apk after.apk
    Size difference in bytes ([*1] apk1 only, [*2] apk2 only):
    +         224 assemblies/Microsoft.Maui.Controls.dll
    +         128 assemblies/Maui.Controls.Sample.dll
    +          24 assemblies/Microsoft.Maui.Controls.Compatibility.dll
    +           4 assemblies/armeabi-v7a/System.Collections.dll
    +           4 assemblies/x86/System.Collections.dll
    -           1 assemblies/arm64-v8a/System.Collections.dll
    -           1 assemblies/Microsoft.Maui.Controls.Xaml.dll
    -           1 assemblies/x86_64/System.Collections.dll
    -          23 assemblies/Microsoft.Extensions.Configuration.Abstractions.dll
    -          70 assemblies/System.Runtime.dll
    -         123 assemblies/System.Security.Cryptography.Primitives.dll
    -         197 assemblies/Microsoft.Extensions.Logging.Abstractions.dll
    -         270 assemblies/Microsoft.Extensions.Configuration.dll
    -       1,125 assemblies/x86/System.Private.CoreLib.dll
    -       1,141 assemblies/armeabi-v7a/System.Private.CoreLib.dll
    -       1,150 assemblies/x86_64/System.Private.CoreLib.dll
    -       1,176 assemblies/arm64-v8a/System.Private.CoreLib.dll
    -       1,216 assemblies/Mono.Android.dll
    -       1,479 assemblies/Microsoft.Extensions.Hosting.Abstractions.dll
    -       3,992 assemblies/Xamarin.Android.Glide.dll
    -       4,096 lib/x86_64/libxamarin-app.so
    -       4,282 assemblies/Microsoft.Extensions.Hosting.dll
    -       6,496 classes.dex
    -      38,724 assemblies/Microsoft.Maui.dll
    Summary:
    +           0 Other entries 0.00% (of 12,105,126)
    -      54,587 Assemblies -0.53% (of 10,222,577)
    -       6,496 Dalvik executables -0.10% (of 6,448,724)
    -       4,096 Shared libraries -0.02% (of 18,457,156)
    -     138,240 Uncompressed assemblies -0.62% (of 22,456,808)
    -      57,344 Package size difference -0.19% (of 30,193,687)

Startup might help a small amount, maybe ~18ms? An average of 10 runs
of a Release build of `Maui.Controls.Sample.SingleProject.csproj` on a
Pixel 5:

    Before: 1.677s
    After:  1.659s